// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whewwtnuslgtstnrbaeb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndoZXd3dG51c2xndHN0bnJiYWViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA2MDEzODksImV4cCI6MjA1NjE3NzM4OX0.bzL0eGtLGxHhT8HP9iP3DPtWqcpApOihmYIOgE2Tku4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
    },
    global: {
      headers: {
        'Content-Type': 'application/json',
        'Prefer': 'return=representation',
      },
    },
  }
);